POST http://localhost:3333/videos
Content-type: application/json

// Informar que tipo de requisição eu irei fazer



{
    "title": "Video node",
    "description": "Esse é o primeiro vídeo",
    "duration": 180
}

###

GET http://localhost:3333/videos

// Informar que tipo de requisição eu irei fazer

###

PUT http://localhost:3333/videos/6d80ad10-9750-45d7-932a-b658fc96d1b2
Content-type: application/json

// Informar que tipo de requisição eu irei fazer



{
    "title": "Video 01",
    "description": "Esse é o vídeo 1, na verdade",
    "duration": 180
}

###

DELETE http://localhost:3333/videos/6d80ad10-9750-45d7-932a-b658fc96d1b2
